### ISSUE TITLE
Not dropping packets destined for other interface

### ISSUE THREAD

**Issue by rhgrant10** [rpgraham84/otptunnel#10]
In the rectify branch, look at line 190.

**Comment by rpgraham84** [comment]
You're right, that jogs my memory a bit. I think the reason our trial run didn't work yesterday was because the command line switches didn't include the remote address. I'm going to try testing again with different switches to see if that was the prob. I think I commented that line out in uncertainty, but I will look into that further.

**Comment by rpgraham84** [comment]
Upon further investigation, that line itself being commented out isn't a problem, but rather former hacked solution to problem that really shouldn't exist in the first place. It will be factored out during code cleanup.
